ALTER TABLE scores
ADD CONSTRAINT fk_scores_users FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE scores
ADD CONSTRAINT fk_scores_games FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE messages
ADD CONSTRAINT fk_messages_games FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE;

ALTER TABLE messages
ADD CONSTRAINT fk_messages_users FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE;
