/* Story 1 */

CREATE TABLE IF NOT EXISTS users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(90) UNIQUE NOT NULL,
    pass VARCHAR(191) NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    date_and_time DATETIME NOT NULL,
    last_connection DATETIME,
    PRIMARY KEY(id)
)

CHARACTER SET 'utf8'
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS scores(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    player_id INT UNSIGNED NOT NULL,
    game_id INT UNSIGNED NOT NULL,
    difficulty ENUM('easy','medium','hard') NOT NULL,
    game_score INT UNSIGNED NOT NULL,
    game_date_and_time DATETIME NOT NULL,
    PRIMARY KEY(id)
)

CHARACTER SET 'utf8'
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS messages(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    sender_id INT UNSIGNED NOT NULL,
    game_id INT UNSIGNED NOT NULL,
    message TEXT NOT NULL,
    message_date_and_time DATETIME NOT NULL,
    PRIMARY KEY(id)
)

CHARACTER SET 'utf8'
ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS games(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    PRIMARY KEY(id)
)

CHARACTER SET 'utf8'
ENGINE=INNODB;

ALTER TABLE scores
ADD CONSTRAINT fk_scores_users FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE scores
ADD CONSTRAINT fk_scores_games FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE messages
ADD CONSTRAINT fk_messages_games FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE messages
ADD CONSTRAINT fk_messages_users FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
